kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    environment: teste
  name: desafio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio
  template:
    metadata:
      labels:
        app: desafio
    spec:
      containers:
      - name: desafio
        imagePullPolicy: Always
        image: us-central1-docker.pkg.dev/winter-surf-452116-n1/desafiodevops1/desafio:desafio-6bf8913
        resources:
          limits:
            memory: "256Mi"
            cpu: "128m"
          requests:
            memory: "128Mi"
            cpu: "64m"
        ports:
        - name: liveness-port
          containerPort: 8080
