---
apiVersion: v1
kind: Service
metadata:
  name: desafio
  namespace: default
  labels:
    app: desafio
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: desafio
  type: ClusterIP
