name: Build and Deploy to GCP
on:
  workflow_dispatch:


env:
  REPOSITORY_NAME: desafio
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ZONE: ${{secrets.GCP_ZONE}}
  GCP_CLUSTER_NAME: ${{secrets.GCP_CLUSTER_NAME}}
  DEPLOYMENT_NAME: desafio
  CONTAINER_NAME: desafio
  NAMESPACE: default
jobs:
  build-and-push-gcp:
    name: Build and push to GCP
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/${{ env.REPOSITORY_NAME }}
        tags: |
          type=sha,enable=true,prefix=desafio-,suffix=,format=short

    - name: Build image and push Google Cloud
      uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
      with:
        registry: ${{ secrets.GCP_ARTIFACT_REGISTRY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}
        image_name: ${{ env.REPOSITORY_NAME }}
        image_tag: ${{ steps.meta.outputs.version }}
        context: ./base-test-api
    - name: Save Image Tag
      run: echo "IMAGE_TAG=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Update kube config
      run: gcloud container clusters get-credentials ${{env.GCP_CLUSTER_NAME}} --zone ${{env.GCP_ZONE}} --project ${{env.GCP_PROJECT_ID}}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{env.GCP_CLUSTER_NAME}}
        location: ${{env.GCP_ZONE}}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/desafio \
          desafio=${{ secrets.GCP_ARTIFACT_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/desafio:$IMAGE_TAG \
          -n default